[package]
name = "openssh-proxy-client"
version = "0.1.0"
edition = "2018"

authors = ["Jiahao XU <Jiahao_XU@outlook.com>"]

license = "MIT"
description = "openssh proxy client for openssh multiplex server."
repository = "https://github.com/openssh-rust/openssh-mux-client"

keywords = ["ssh", "openssh", "multiplex", "async", "network"]
categories = ["asynchronous", "network-programming", "api-bindings"]

[dependencies]
awaitable = "0.3.3"
bytes = "1.2.1"
serde = { version = "1.0.103", features = ["derive"] }
ssh_format = "0.13.2"
thiserror = "1.0.29"
tokio = { version = "1.11.0", features = ["rt", "io-util"] }
tokio-io-utility = "0.7.1"
