version: 2
updates:
  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/crates/mux-client"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/crates/mux-client-error"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/crates/proxy-client"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/crates/proxy-client-error"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/crates/non-zero-byte-slice"
    schedule:
      interval: "daily"
