[package]
name = "openssh-mux-client"
version = "0.1.0"
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
ssh_mux_format = "0.4.3"
sendfd = "0.3.3"
tokio = { version = "1.11.0", features = ["net"] }
typed-builder = "0.9.1"
once_cell = "1.8.0"

[dev-dependencies]
tokio = { version = "1.11.0", features = ["rt", "macros"] }
tokio-pipe = "0.2.1"
