[package]
name = "openssh-mux-client"
version = "0.1.0"
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
ssh_mux_format = "0.4.3"
sendfd = { version = "0.4.0", features = ["tokio"] }
tokio = { version = "1.11.0", features = ["net"] }
typed-builder = "0.9.1"
once_cell = "1.8.0"

[dev-dependencies]
tokio = { version = "1.11.0", features = ["rt", "macros", "io-util"] }
tokio-pipe = "0.2.1"
assert_matches = "1.5.0"
