[package]
name = "openssh-mux-client"
version = "0.1.0"
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
ssh_mux_format = "0.3.4"
passfd = "0.1.4"
tokio = { version = "1.11.0", features = ["net"] }
