[package]
name = "openssh-mux-client"
version = "0.1.1"
edition = "2018"

authors = ["Jiahao XU <Jiahao_XU@outlook.com>"]

license = "GPL-2.0"
description = "Data format used to communicate with openssh mux server."
repository = "https://github.com/NobodyXu/ssh_mux_format"

keywords = ["ssh", "openssh", "multiplex", "async"]
categories = ["asynchronous", "network-programming"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
ssh_mux_format = "0.4.3"
sendfd = { version = "0.4.0", features = ["tokio"] }
tokio = { version = "1.11.0", features = ["net"] }
typed-builder = "0.9.1"
once_cell = "1.8.0"
thiserror = "1.0.29"

[dev-dependencies]
tokio = { version = "1.11.0", features = ["rt", "macros", "io-util"] }
tokio-pipe = "0.2.1"
assert_matches = "1.5.0"
