name: Rust

on: [push, pull_request]
  paths-ignore:
    - 'README.md'
    - 'LICENSE'
    - '.gitignore'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: |
        ./run_test.sh
        cargo check
        cargo fmt --all -- --check
        cargo clippy
